<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="old\**" />
    <Compile Remove="ProgramFiles\SysInterfaces\NodeManagement\NodeAggregate\NewFolder\**" />
    <Compile Remove="ProgramFiles\SysInterfaces\NodeManagement\NodeAggregate\Application\**" />
    <Compile Remove="ProgramFiles\SysInterfaces\NodeManagement\NodeAggregate\Infrastructure\**" />
    <EmbeddedResource Remove="old\**" />
    <EmbeddedResource Remove="ProgramFiles\SysInterfaces\NodeManagement\NodeAggregate\NewFolder\**" />
    <EmbeddedResource Remove="ProgramFiles\SysInterfaces\NodeManagement\NodeAggregate\Application\**" />
    <EmbeddedResource Remove="ProgramFiles\SysInterfaces\NodeManagement\NodeAggregate\Infrastructure\**" />
    <None Remove="old\**" />
    <None Remove="ProgramFiles\SysInterfaces\NodeManagement\NodeAggregate\NewFolder\**" />
    <None Remove="ProgramFiles\SysInterfaces\NodeManagement\NodeAggregate\Application\**" />
    <None Remove="ProgramFiles\SysInterfaces\NodeManagement\NodeAggregate\Infrastructure\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="ProgramFiles\SysInterfaces\NodeManagement\NodeAggregate\Application\INoteService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ProgramData\" />
    <Folder Include="ProgramFiles\SysImplementation\" />
    <Folder Include="ProgramFiles\SysInterfaces\ViewManagement\" />
  </ItemGroup>

</Project>