<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="old\**" />
    <Compile Remove="ProgramFiles\NewFolder\**" />
    <Compile Remove="ProgramFiles\SysAbstractModules\NodeContext\NodeAggregate\NewFolder\**" />
    <Compile Remove="ProgramFiles\SysAbstractModules\NodeContext\NodeAggregate\Application\**" />
    <EmbeddedResource Remove="old\**" />
    <EmbeddedResource Remove="ProgramFiles\NewFolder\**" />
    <EmbeddedResource Remove="ProgramFiles\SysAbstractModules\NodeContext\NodeAggregate\NewFolder\**" />
    <EmbeddedResource Remove="ProgramFiles\SysAbstractModules\NodeContext\NodeAggregate\Application\**" />
    <None Remove="old\**" />
    <None Remove="ProgramFiles\NewFolder\**" />
    <None Remove="ProgramFiles\SysAbstractModules\NodeContext\NodeAggregate\NewFolder\**" />
    <None Remove="ProgramFiles\SysAbstractModules\NodeContext\NodeAggregate\Application\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ProgramData\" />
    <Folder Include="ProgramFiles\BoundedContext\Feature\Application\" />
    <Folder Include="ProgramFiles\BoundedContext\Feature\Domain\" />
    <Folder Include="ProgramFiles\BoundedContext\Feature\Infrastructure\" />
    <Folder Include="ProgramFiles\SysAbstractModules\NodeContext\NodeAggregate\Application\" />
    <Folder Include="ProgramFiles\SysAbstractModules\NodeContext\NodeAggregate\Domain\" />
    <Folder Include="ProgramFiles\SysAbstractModules\NodeContext\NodeAggregate\Infrastructure\" />
    <Folder Include="ProgramFiles\SysAbstractModules\NodeContext\Node\Infrastructure\" />
    <Folder Include="ProgramFiles\SysAbstractModules\NodeContext\Link\Application\" />
    <Folder Include="ProgramFiles\SysAbstractModules\NodeContext\Link\Infrastructure\" />
    <Folder Include="ProgramFiles\SysAbstractModules\NodeContext\Note\Infrastructure\" />
    <Folder Include="ProgramFiles\SysAbstractModules\ViewContext\" />
  </ItemGroup>

</Project>